name: Build & Deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - run: go install github.com/googlecodelabs/tools/claat@latest

      - uses: actions/cache@@v3
        id: cache-npm-packages
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM dependencies (/site)
        if: steps.cache-npm-packages.outputs.cache-hit != 'true'
        working-directory: ./site/
        run: npm ci

      - name: Build
        working-directory: ./site/
        run: npx gulp dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/dist
